export const cardID = new Map([
  ['colonizer training camp', '001'],
  ['asteroid mining consortium', '002'],
  ['deep well heating', '003'],
  ['cloud seeding', '004'],
  ['search for life', '005'],
  ['inventors guild', '006'],
  ['martian rails', '007'],
  ['capital', '008'],
  ['asteroid', '009'],
  ['comet', '010'],
  ['big asteroid', '011'],
  ['water import from europa', '012'],
  ['space elevator', '013'],
  ['development center', '014'],
  ['equatorial magnetizer', '015'],
  ['domed crater', '016'],
  ['noctis city', '017'],
  ['methane from titan', '018'],
  ['imported hydrogen', '019'],
  ['research outpost', '020'],
  ['phosbos space haven', '021'],
  ['black polar dust', '022'],
  ['arctic algae', '023'],
  ['predators', '024'],
  ['space station', '025'],
  ['eos chasma national park', '026'],
  ['interstellar colony ship', '027'],
  ['security fleet', '028'],
  ['cupola city', '029'],
  ['lunar beam', '030'],
  ['optimal aerobraking', '031'],
  ['underground city', '032'],
  ['regolith eaters', '033'],
  ['ghg producing bacteria', '034'],
  ['ants', '035'],
  ['release of inert gases', '036'],
  ['nitrogen-rch asteroid', '037'],
  ['rover construction', '038'],
  ['deimos down', '039'],
  ['asteroid mining', '040'],
  ['food factory', '041'],
  ['archaebacteria', '042'],
  ['carbonate processing', '043'],
  ['natural preserve', '044'],
  ['nuclear power', '045'],
  ['lightning harvest', '046'],
  ['algae', '047'],
  ['adapted lichen', '048'],
  ['tardigrades', '049'],
  ['virus', '050'],
  ['miranda resort', '051'],
  ['fish', '052'],
  ['lake marineris', '053'],
  ['small animals', '054'],
  ['kelp farming', '055'],
  ['mine', '056'],
  ['vesta shipyard', '057'],
  ['beam from thorium asteroid', '058'],
  ['mangrove', '059'],
  ['trees', '060'],
  ['great escarpment consortium', '061'],
  ['mineral depost', '062'],
  ['mining expedition', '063'],
  ['mining area', '064'],
  ['building industries', '065'],
  ['land claim', '066'],
  ['mining rights', '067'],
  ['sponsors', '068'],
  ['electro catapult', '069'],
  ['earth catapult', '070'],
  ['advanced alloys', '071'],
  ['birds', '072'],
  ['mars university', '073'],
  ['viral enhancers', '074'],
  ['towing a comet', '075'],
  ['space mirrors', '076'],
  ['solar wind power', '077'],
  ['ice asteroid', '078'],
  ['quantum extractor', '079'],
  ['giant ice asteroid', '080'],
  ['ganymede colony', '081'],
  ['callisto penal mines', '082'],
  ['giant space mirror', '083'],
  ['trans-neptune probe', '084'],
  ['commercial district', '085'],
  ['robotic workforce', '086'],
  ['grass', '087'],
  ['heather', '088'],
  ['peroxide power', '089'],
  ['research', '090'],
  ['gene repair', '091'],
  ['io mining industries', '092'],
  ['bushes', '093'],
  ['mass converter', '094'],
  ['physics complex', '095'],
  ['greenhouses', '096'],
  ['nuclear zone', '097'],
  ['tropical resort', '098'],
  ['toll station', '099'],
  ['fueled generators', '100'],
  ['ironworks', '101'],
  ['power grid', '102'],
  ['steelworks', '103'],
  ['ore processor', '104'],
  ['earth office', '105'],
  ['acquired company', '106'],
  ['media archives', '107'],
  ['open city', '108'],
  ['media group', '109'],
  ['business network', '110'],
  ['business contacts', '111'],
  ['bribed committee', '112'],
  ['solar power', '113'],
  ['breathing filters', '114'],
  ['artificial photosynthesis', '115'],
  ['artificial lake', '116'],
  ['geothermal power', '117'],
  ['farming', '118'],
  ['dust seals', '119'],
  ['urbanized area', '120'],
  ['sabotage', '121'],
  ['moss', '122'],
  ['industrial center', '123'],
  ['hired raiders', '124'],
  ['hackers', '125'],
  ['ghg factories', '126'],
  ['subterranean reservoir', '127'],
  ['ecological zone', '128'],
  ['zeppelins', '129'],
  ['worms', '130'],
  ['decomposers', '131'],
  ['fusion power', '132'],
  ['symbiotic fungus', '133'],
  ['extreme-cold fungus', '134'],
  ['advanced ecosystems', '135'],
  ['great dam', '136'],
  ['cartel', '137'],
  ['strip mine', '138'],
  ['wave power', '139'],
  ['lava flows', '140'],
  ['power plant', '141'],
  ['mohole area', '142'],
  ['large convoy', '143'],
  ['titanium mine', '144'],
  ['tectonic stress power', '145'],
  ['nitrophilic moss', '146'],
  ['herbivores', '147'],
  ['insects', '148'],
  ['ceos favorite project', '149'],
  ['anti-gravity technology', '150'],
  ['investment loan', '151'],
  ['insulation', '152'],
  ['adaptation technology', '153'],
  ['caretaker contract', '154'],
  ['designed microorganisms', '155'],
  ['standard technology', '156'],
  ['nitrite reducing bacteria', '157'],
  ['industrial microbes', '158'],
  ['lichen', '159'],
  ['power supply consortium', '160'],
  ['convoy from europa', '161'],
  ['imported ghg', '162'],
  ['imported nitrogen', '163'],
  ['micro-mills', '164'],
  ['magnetic field generators', '165'],
  ['shuttles', '166'],
  ['import of advanced ghg', '167'],
  ['windmills', '168'],
  ['tundra farming', '169'],
  ['aerobraked ammonia asteroid', '170'],
  ['magnetic field dome', '171'],
  ['pets', '172'],
  ['protected habitats', '173'],
  ['protected valley', '174'],
  ['satellites', '175'],
  ['noctis farming', '176'],
  ['water splitting plant', '177'],
  ['heat trappers', '178'],
  ['soil factory', '179'],
  ['fuel factory', '180'],
  ['ice cap melting', '181'],
  ['corporate stronghold', '182'],
  ['biomass combustors', '183'],
  ['livestock', '184'],
  ['olympus conference', '185'],
  ['rad-suits', '186'],
  ['aquifer pumping', '187'],
  ['flooding', '188'],
  ['energy saving', '189'],
  ['local heat trapping', '190'],
  ['permafrost extraction', '191'],
  ['invention contest', '192'],
  ['plantation', '193'],
  ['power infrastructure', '194'],
  ['indentured workers', '195'],
  ['lagrange observatory', '196'],
  ['terraforming ganymede', '197'],
  ['immigration shuttles', '198'],
  ['restricted area', '199'],
  ['immigrant city', '200'],
  ['energy tapping', '201'],
  ['underground detonation', '202'],
  ['soletta', '203'],
  ['technology demonstration', '204'],
  ['rad-chem factory', '205'],
  ['special design', '206'],
  ['medical lab', '207'],
  ['ai central', '208'],
  ['small asteroid', '209'],
  ['self-replicating robots', '210'],
  ['snow algae', '211'],
  ['penguins', '212'],
  ['aerial mappers', '213'],
  ['aerosport tournament', '214'],
  ['air-scrapping expedition', '215'],
  ['atalanta palnitia lab', '216'],
  ['atmoscoop', '217'],
  ['comet for venus', '218'],
  ['cooroder suits', '219'],
  ['dawn city', '220'],
  ['deuterium export', '221'],
  ['dirigibles', '222'],
  ['extractor balloons', '223'],
  ['extremophiles', '224'],
  ['floating habs', '225'],
  ['forced precipitation', '226'],
  ['freyja biodomes', '227'],
  ['ghg import from venus', '228'],
  ['giant solar shade', '229'],
  ['gyropolis', '230'],
  ['hydrogen to venus', '231'],
  ['io sulphur research', '232'],
  ['ishtar mining', '233'],
  ['jet stream microscrappers', '234'],
  ['local shading', '235'],
  ['luna metropolis', '236'],
  ['luxury foods', '237'],
  ['maxwell base', '238'],
  ['mining quota', '239'],
  ['neutralizer factory', '240'],
  ['omnicourt', '241'],
  ['orbital reflectors', '242'],
  ['rotator impacts', '243'],
  ['sister planet support', '244'],
  ['solarnet', '245'],
  ['spin-inducing asteroid', '246'],
  ['sponsored academies', '247'],
  ['stratopolis', '248'],
  ['stratospheric birds', '249'],
  ['sulphur exports', '250'],
  ['sulphur-eating bacteria', '251'],
  ['terraforming contract', '252'],
  ['thermophiles', '253'],
  ['water to venus', '254'],
  ['venus governor', '255'],
  ['venus magnetizer', '256'],
  ['venus soils', '257'],
  ['venus waystation', '258'],
  ['venusian animals', '259'],
  ['venusian insects', '260'],
  ['venusian plants', '261'],
  ['house printing', 'p36'],
  ['lava tube settlement', 'p37'],
  ['martian survey', 'p38'],
  ['psychrophiles', 'p39'],
  ['research coordination', 'p40'],
  ['sf memorial', 'p41'],
  ['space hotels', 'p42'],
  ['airliners', 'c01'],
  ['air raid', 'c02'],
  ['atmo collectors', 'c03'],
  ['community services', 'c04'],
  ['conscription', 'c05'],
  ['corona extractor', 'c06'],
  ['cryo sleep', 'c07'],
  ['earth elevator', 'c08'],
  ['ecology research', 'c09'],
  ['floater leasing', 'c10'],
  ['floater prototypes', 'c11'],
  ['floater technology', 'c12'],
  ['galilean waystation', 'c13'],
  ['heavy taxation', 'c14'],
  ['ice moon colony', 'c15'],
  ['impactor swarm', 'c16'],
  ['interplanetary colony ship', 'c17'],
  ['jovian lanterns', 'c18'],
  ['jupiter floating station', 'c19'],
  ['luna governor', 'c20'],
  ['lunar exports', 'c21'],
  ['lunar mining', 'c22'],
  ['market manipulation', 'c23'],
  ['martian zoo', 'c24'],
  ['mining colony', 'c25'],
  ['minority refuge', 'c26'],
  ['molecular printing', 'c27'],
  ['nitrogen from titan', 'c28'],
  ['pioneer settlement', 'c29'],
  ['productive outpost', 'c30'],
  ['quantum communications', 'c31'],
  ['red spot observatory', 'c32'],
  ['refugee camps', 'c33'],
  ['research colony', 'c34'],
  ['rim freighters', 'c35'],
  ['sky docks', 'c36'],
  ['solar probe', 'c37'],
  ['solar reflectors', 'c38'],
  ['space port', 'c39'],
  ['space port colony', 'c40'],
  ['spin-off department', 'c41'],
  ['sub-zero salt fish', 'c42'],
  ['titan air-scrapping', 'c43'],
  ['titan floating launch-pad', 'c44'],
  ['titan shuttles', 'c45'],
  ['trade envoys', 'c46'],
  ['trading colony', 'c47'],
  ['urban decomposers', 'c48'],
  ['warp drive', 'c49'],
  ['aerial lenses', 't01'],
  ['banned delegate', 't02'],
  ['cultural metropolis', 't03'],
  ['diaspora movement', 't04'],
  ['event analysts', 't05'],
  ['gmo contract', 't06'],
  ['martian media center', 't07'],
  ['parliament hall', 't08'],
  ['pr office', 't09'],
  ['public celebrations', 't10'],
  ['recruitment', 't11'],
  ['red tourism wave', 't12'],
  ['sponsored mohole', 't13'],
  ['supported research', 't14'],
  ['wildlife dome', 't15'],
  ['vote of no confidence', 't16'],
  ['dusk laser mining', 'x01'],
  ['project inspection', 'x02'],
  ['energy market', 'x03'],
  ['hi-tech lab', 'x04'],
  ['interplanetary trade', 'x05'],
  ['law suit', 'x06'],
  ['mercurian alloys', 'x07'],
  ['orbital cleanup', 'x08'],
  ['political alliance', 'x09'],
  ['rego plastics', 'x10'],
  ['saturn surfing', 'x11'],
  ['stanford torus', 'x12'],
  ['asteroid hollowing', 'x13'],
  ['advertising', 'x14'],
  ['comet aiming', 'x15'],
  ['crash site cleanup', 'x16'],
  ['cutting edge technology', 'x17'],
  ['directed impactors', 'x18'],
  ['field-capped city', 'x19'],
  ['magnetic field', 'x20'],
  ['meltworks', 'x21'],
  ['mohole lake', 'x22'],
  ['diversity support', 'x23'],
  ['jovian embassy', 'x24'],
  ['topsoil contract', 'x25'],
  ['imported nutrients', 'x26'],
  ['asteroid deflection system', 'x27'],
  ['sub-crust measurements', 'x28'],
  ['potatoes', 'x29'],
  ['meat industries', 'x30'],
  ['credicor', 'corp01'],
  ['ecoline', 'corp02'],
  ['helion', 'corp03'],
  ['mining guild', 'corp04'],
  ['interplanetary cinematics', 'corp05'],
  ['inventrix', 'corp06'],
  ['phobolog', 'corp07'],
  ['tharsis republic', 'corp08'],
  ['thorgate', 'corp09'],
  ['united nations mars initiative', 'corp10'],
  ['teractor', 'corp11'],
  ['saturn systems', 'corp12'],
  ['aphrodite', 'corp13'],
  ['celestic', 'corp14'],
  ['manutech', 'corp15'],
  ['morning star inc', 'corp16'],
  ['viron', 'corp17'],
  ['cheung shing mars', 'corp18'],
  ['point luna', 'corp19'],
  ['robinson industries', 'corp20'],
  ['valley trust', 'corp21'],
  ['vitor', 'corp22'],
  ['aridor', 'corp23'],
  ['arklight', 'corp24'],
  ['polyphemos', 'corp25'],
  ['poseidon', 'corp26'],
  ['storm craft', 'corp27'],
  ['lakefront resorts', 'corp28'],
  ['pristar', 'corp29'],
  ['septem tribus', 'corp30'],
  ['terralabs', 'corp31'],
  ['utopia invest', 'corp32'],
  ['factorum', 'corp33'],
  ['mons insurance', 'corp34'],
  ['philares', 'corp35'],
  ['arcadian communities', 'corp36'],
  ['recyclon', 'corp37'],
  ['splice', 'corp38'],
  ['astrodrill', 'corp39'],
  ['pharmacy union', 'corp40'],
  ['allied banks', 'p01'],
  ['aquifer turbines', 'p02'],
  ['biofuels', 'p03'],
  ['biolab', 'p04'],
  ['biosphere support', 'p05'],
  ['business empire', 'p06'],
  ['dome farming', 'p07'],
  ['donation', 'p08'],
  ['early settlement', 'p09'],
  ['ecology experts', 'p10'],
  ['eccentric sponsor', 'p11'],
  ['experimental forest', 'p12'],
  ['galilean mining', 'p13'],
  ['great aquifer', 'p14'],
  ['huge asteroid', 'p15'],
  ['io research outpost', 'p16'],
  ['loan', 'p17'],
  ['martian industries', 'p18'],
  ['metal-rich asteroid', 'p19'],
  ['metal company', 'p20'],
  ['mining operations', 'p21'],
  ['mohole', 'p22'],
  ['mohole excavation', 'p23'],
  ['nitrogen shipment', 'p24'],
  ['orbital construction yard', 'p25'],
  ['polar industries', 'p26'],
  ['power generation', 'p27'],
  ['research network', 'p28'],
  ['self-sufficient settlement', 'p29'],
  ['smelting plant', 'p30'],
  ['society support', 'p31'],
  ['supplier', 'p32'],
  ['supply drop', 'p33'],
  ['unmi contractor', 'p34'],
  ['acquired space agency', 'p35'],
  ['colony europa', 'EUROPA'],
  ['colony triton', 'TRITON'],
  ['colony callisto', 'CALLISTO'],
  ['colony ceres', 'CERES'],
  ['colony enceladus', 'ENCELADUS'],
  ['colony titan', 'TITAN'],
  ['colony miranda', 'MIRANDA'],
  ['colony ganymede', 'GANYMEDE'],
  ['colony luna', 'LUNA'],
  ['colony io', 'IO'],
  ['colony pluto', 'PLUTO']
]);

export const microbeCards = [
  'regolith eaters',
  'ghg producing bacteria',
  'ants',
  'archaebacteria',
  'tardigrades',
  'virus',
  'viral enhancers',
  'worms',
  'decomposers',
  'symbiotic fungus',
  'extreme-cold fungus',
  'advanced ecosystems',
  'insects',
  'designed microorganisms',
  'nitrite reducing bacteria',
  'industrial microbes',
  'extremophiles',
  'sulphur-eating bacteria',
  'thermophiles',
  'venusian insects',
  'psychrophiles',
  'ecology research',
  'urban decomposers',
  'gmo contract',
  'topsoil contract'
];

export const otherLifeCards = [
  'arctic algae',
  'predators',
  'eos chasma national park',
  'algae',
  'adapted lichen',
  'fish',
  'small animals',
  'kelp farming',
  'mangrove',
  'trees',
  'birds',
  'grass',
  'heather',
  'bushes',
  'greenhouses',
  'farming',
  'moss',
  'ecological zone',
  'advanced ecosystems',
  'nitrophilic moss',
  'herbivores',
  'lichen',
  'tundra farming',
  'pets',
  'protected valley',
  'noctis farming',
  'livestock',
  'plantation',
  'snow algae',
  'penguins',
  'freyja biodomes',
  'stratospheric birds',
  'venus soils',
  'venusian animals',
  'venusian plants',
  'ecology research',
  'martian zoo',
  'sub-zero salt fish',
  'wildlife dome',
  'potatoes'
];
